### ISSUE TITLE
Feature: Saved settings&filters across devices

### ISSUE THREAD

**Issue by RobertKorteweg** [WatWowMap/ReactMap#419]
This is a feature request, if this is not something you can or will do, feel free to close this issue.

I would like to be able to have my map settings and filters saved for when I login again on other devices. I believe current workings are cookies saved per device. If this is possible this should be saved on the server or somehow through the discord login.

**Comment by clburlison** [comment]
I don't believe this is going to be a good idea. The settings for this front end are quite extensive. Even if we hashed all the settings to make it easier to save in the database this would be a ton of additional read/writes each time a setting got modified. In general it would just be a bad user experience.

**Comment by TurtIeSocks** [comment]
Yeah... If you export the settings JSON you can see just how many different values there are. It's tens of thousands per user, which would quickly get out of hand, unfortunately. 

That being said, I did write a feature for backing up the entire JSON in the database, then users could load the backup into their local storage for each of their devices. I never finished it though because it felt "wrong" loading giant JSONs into MySQL but maybe I should just accept that it's better than nothing.

**Comment by RobertKorteweg** [comment]
Thanks for the fast response! I understand if you would update the settings every change that would be a lot of data each time and thus waiting times.

If I read the Turtlesocks comment correctly, a place to store 1 set of settings/filters, that would be awesome. This way people also would have a choice to use the stored set or stay with a local set. 

I downloaded the settings file and storing that entire file would also be a lot of data. I was wandering is it not better to just store the users changes? So make a "default" set and just store the changes a user makes in that set. In the default set everything would be turned off, i believe that would significantly large impact to the settings file.

**Comment by TurtIeSocks** [comment]
Closing this for now... I think this is really going to have to be addressed in a completely new version of RM. We're too deep in at this point for this project, at least that's how I feel. If someone else wants to PR, they're welcome to but god speed.
