### ISSUE TITLE
Hide Gyms with badges

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#541]
I received some suggestions from map users that an option to hide all Gyms with badges would be very handy in collecting badges. Proly an easy switch or sth would do the job

**Comment by Fabio1988** [comment]
And some users reported some suggestions to me too:
Only show those gyms which has badges defined, don't show others if gym badges is enabled.

Because that city has about 1500 gyms, and those users only want to collect badges of a certain area (self defined), so it would be a huge increasement only to show defined badges for them :)

**Comment by Speedpete81** [comment]
I think this could be done with some kind of user accounts / user settings.
They may predefine their gyms they are interested in and hide the rest.

You may also think a little bit further, could also work good for hundo hunting without the poracle integration (directly on the map)

**Comment by kamieniarz** [comment]
Done in #745. Thanks Turtle!
