### ISSUE TITLE
Allow dual configuration via local.json and environment variables

### ISSUE THREAD

**Issue by DrMurx** [WatWowMap/ReactMap#677]
The current `config.js` falls back to environment variables only if `local.json` [doesn't exist](https://github.com/WatWowMap/ReactMap/blob/3117c1d77ef60198a5ae9041b4345c26e1c97ae7/server/src/services/config.js#L47). There's good reason to use both at the same time (ie. configure the database with variables but the map details with `local.json`), so why not allow both to coexist?

**Comment by TurtIeSocks** [comment]
These are special env variables. You can set [every single env variable](https://github.com/WatWowMap/ReactMap/blob/main/server/src/configs/custom-environment-variables.json) instead of a `local.json` if desired. 

The ones that are blocked if a `local.json` is present are only meant to be for a "quick start setup". Due to ReactMap's ability to connect to any number of databases and customize each one with specific categories of data from each, it is not recommended to use these env variables in the long run anyway.
